package app

var store = map[ApplicationStatus]Step{
	StartApply: Step{
		name:                    StartApply,
		desc:                    "Start of the application, the candidate applies for a job.%s%s",
		defaultRecuirterAction:  Recive,
		defaultcandidateAction:  Apply,
		recuirterAllowedActions: []Action{},
		candidateAllowedActions: []Action{Apply},
		nextStep:                AfterApply,
	},
	AfterApply: Step{
		name:                    AfterApply,
		desc:                    "After the applying step, the recruiter can [%s] the application. The candidate can [%s] the application.",
		defaultRecuirterAction:  nothing,
		defaultcandidateAction:  Accept,
		recuirterAllowedActions: []Action{Accept, Reject},
		candidateAllowedActions: []Action{Cancel},
		nextStep:                StartInterview,
	},
	StartSchedule: Step{
		name:                    StartSchedule,
		desc:                    "Start the appointment scheduling step, the recruiter can [%s] the interview. The candidate has to [%s] for the interview.",
		defaultRecuirterAction:  Accept,
		defaultcandidateAction:  nothing,
		recuirterAllowedActions: []Action{Cancel},
		candidateAllowedActions: []Action{Submitdate, Cancel},
		nextStep:                AfterSchedule,
	},
	AfterSchedule: Step{
		name:                    AfterSchedule,
		desc:                    "After the appointment scheduling step, the recruiter can [%s] date for interview. The candidate can [%s] the process",
		defaultRecuirterAction:  nothing,
		defaultcandidateAction:  Accept,
		recuirterAllowedActions: []Action{Cancel, Fixdate, Reschedule},
		candidateAllowedActions: []Action{Cancel},
		nextStep:                StartInterview,
	},
	StartInterview: Step{
		name:                    StartInterview,
		desc:                    "Start the interview step, the recuiter can [%s] the interview. The candidate can [%s] the interview",
		defaultRecuirterAction:  Accept,
		defaultcandidateAction:  nothing,
		recuirterAllowedActions: []Action{Cancel, Skip},
		candidateAllowedActions: []Action{Accept, Reject},
		nextStep:                AfterInterview,
	},
	AfterInterview: Step{
		name:                    AfterInterview,
		desc:                    "After the interview step, the recruiter can [%s] the interview. The candidate can [%s] the interview.",
		defaultRecuirterAction:  nothing,
		defaultcandidateAction:  Accept,
		recuirterAllowedActions: []Action{Accept, Reject, Skip},
		candidateAllowedActions: []Action{Decline},
		nextStep:                Offer,
	},
	Offer: Step{
		name:                    Offer,
		desc:                    "The offer step, the recruiter can [%s]. The candidate can [%s] the offer.",
		defaultRecuirterAction:  Accept,
		defaultcandidateAction:  nothing,
		recuirterAllowedActions: []Action{Cancel},
		candidateAllowedActions: []Action{Accept, Decline},
		nextStep:                Closed,
	},
	Closed: Step{
		name:                    Closed,
		desc:                    "Closing application step, the application is colsed and archived.%s%s",
		defaultRecuirterAction:  nothing,
		defaultcandidateAction:  nothing,
		recuirterAllowedActions: []Action{},
		candidateAllowedActions: []Action{},
	},
}
